name: CD - Promote to Production

on:
  repository_dispatch:
    types: [cd-dispatch-event]

env:
    web_image: mywebappnode
    nginx_image: mynginxnode
    
  
jobs:
  promote:
    runs-on: ubuntu-latest
    environment: production
    steps:
      - name: Login to Docker Hub
        uses: docker/login-action@v4
        with:
          username: ${{ vars.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      - name: Pull images
        run: |
          docker pull docker.io/${{ vars.DOCKERHUB_USERNAME }}/${{env.web_image}}:${{ github.event.client_payload.sha }}
          docker pull docker.io/${{ vars.DOCKERHUB_USERNAME }}/${{env.nginx_image}}:${{ github.event.client_payload.sha }}

      - name: Tag as production
        run: |
          docker tag \
            docker.io/${{ vars.DOCKERHUB_USERNAME }}/${{env.web_image}}:${{ github.event.client_payload.sha }} \
            docker.io/${{ vars.DOCKERHUB_USERNAME }}/${{env.web_image}}:prod

          docker tag \
            docker.io/${{ vars.DOCKERHUB_USERNAME }}/${{env.nginx_image}}:${{ github.event.client_payload.sha }} \
            docker.io/${{ vars.DOCKERHUB_USERNAME }}/${{env.nginx_image}}:prod

      - name: Push production tags
        run: |
          docker push docker.io/${{ vars.DOCKERHUB_USERNAME }}/${{env.web_image}}:prod
          docker push docker.io/${{ vars.DOCKERHUB_USERNAME }}/${{env.nginx_image}}:prod